{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-documenter
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/documenter_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/documenter/documenter_{{ version }}.tar.gz
  sha256: c480896cdd08d8a37648958a08924b56213a83878248b5ab6abe9f0ac154fc2b

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-magrittr
    - r-officer
    - r-yaml
  run:
    - r-base
    - r-htmltools
    - r-magrittr
    - r-officer
    - r-yaml

test:
  commands:
    - $R -e "library('documenter')"           # [not win]
    - "\"%R%\" -e \"library('documenter')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=documenter
  license: MIT
  summary: It is sometimes necessary to create documentation for all files in a directory. Doing so by hand can be very tedious. This task is made fast and reproducible using the functionality of 'documenter'. It aggregates all text files in a directory and its subdirectories into a single word document in a semi-automated
    fashion.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
